import React from 'react';
import { useNavigate } from 'react-router-dom';
const About = () => {
    const navigate=useNavigate();
  return (
    <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu velit at sapien porta pulvinar. Sed vitae consectetur orci. Quisque in neque ac neque venenatis finibus sit amet nec lorem. Proin ultricies, velit vitae eleifend mattis, purus nunc vestibulum mi, et euismod ligula diam at dolor. Donec id neque sed orci bibendum vulputate vel vitae orci. Suspendisse vitae est ut ligula interdum dignissim sit amet a velit. Ut eu lacinia mauris. Etiam ut facilisis mi. In hac habitasse platea dictumst. Etiam porttitor felis sed commodo congue.

Nulla facilisi. Suspendisse malesuada quam scelerisque massa vulputate, eget suscipit erat fringilla. In accumsan tortor in velit tristique, id aliquam risus dignissim. Sed justo ligula, suscipit sit amet viverra in, gravida ut ante. Praesent scelerisque, erat ac finibus sagittis, quam leo vestibulum nisl, at hendrerit nisi mi non sem. Integer in odio nibh. Ut non consectetur neque, ut suscipit lectus. Aenean convallis tincidunt iaculis.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris sollicitudin nulla erat, quis pharetra lacus placerat a. Aliquam a massa enim. Nullam posuere nibh nisi, sed mattis magna pharetra sed. Vestibulum in ligula in lorem congue commodo a non eros. Proin ut convallis risus, nec feugiat ligula. Quisque eget sapien leo.

Cras ultrices mollis massa, a sagittis leo sodales et. Morbi venenatis nec tortor ut dictum. Maecenas aliquet felis lacus, at aliquam augue porttitor nec. In sem enim, pulvinar eget neque vitae, placerat posuere mi. Mauris sit amet mi id lacus iaculis commodo. Nullam ligula mi, dictum quis velit eget, lacinia pharetra nisi. Nunc venenatis lectus et elit placerat, ac pretium orci feugiat. Sed diam ex, sagittis volutpat posuere sed, mollis eget leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas in justo in enim gravida varius fermentum aliquam sem. Ut euismod rutrum auctor.

Curabitur dictum ante diam, at rhoncus dolor auctor vitae. Vestibulum neque metus, blandit in efficitur eu, bibendum at nulla. Integer vel risus tellus. Ut ullamcorper nibh fermentum dignissim varius. Proin at lorem sit amet lectus ultricies dignissim eu eget sapien. Quisque efficitur a neque quis mattis. Ut suscipit vestibulum luctus. Mauris facilisis risus ut sem placerat vulputate.

Nam libero turpis, dignissim a urna nec, efficitur maximus ligula. Ut a blandit odio. Suspendisse potenti. Phasellus eleifend dapibus ante, eget pulvinar lacus tempor et. Donec non mollis leo. Morbi venenatis tempus sem, eget dignissim leo posuere id. Curabitur sit amet nulla aliquam, vehicula odio ut, luctus velit. Nullam odio nulla, congue et pharetra eu, consequat et risus.

Suspendisse viverra cursus libero et aliquet. Vivamus condimentum tempus justo, ut dictum ante. Sed sit amet interdum velit. Vestibulum nunc elit, consequat nec nibh nec, aliquam suscipit tortor. Mauris auctor non dolor vel consectetur. Nunc sed viverra magna. Donec libero enim, varius condimentum sem sed, euismod viverra quam.

Vivamus pellentesque sapien purus, at accumsan risus tempus nec. Vestibulum porta ut augue ut porttitor. Pellentesque dui eros, sagittis eu risus in, finibus posuere orci. Praesent viverra pharetra mauris, ac feugiat leo commodo eget. Suspendisse turpis eros, tempor imperdiet blandit vel, faucibus ut neque. Aenean mattis metus eget imperdiet placerat. Duis ultrices posuere ultricies. Pellentesque eu felis quis elit faucibus mollis. Praesent hendrerit tempor lectus in consectetur. Nam dapibus arcu in tellus suscipit, ac fringilla nibh sollicitudin. Mauris sodales, velit a pharetra rutrum, purus odio efficitur quam, sed aliquam nisl libero ac metus.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin interdum nec est vel scelerisque. Ut a cursus lacus, quis congue augue. Sed dui ex, malesuada non vulputate non, pretium id nibh. Integer ultrices nisi metus, condimentum feugiat sapien posuere ut. Morbi condimentum orci iaculis neque mollis dapibus. In sed hendrerit lorem. Phasellus laoreet, nibh sit amet tincidunt sollicitudin, ante purus mattis turpis, vel pharetra lacus est a risus. Vivamus porta libero in sem lobortis posuere. Fusce ullamcorper ipsum tellus, et eleifend sapien ultricies et. Quisque vitae eros id ex consectetur blandit et in est. Sed eget interdum quam, vitae ultrices sapien.

Cras quis ullamcorper nisl. Sed ac consectetur quam, vitae luctus libero. Fusce mollis mauris a enim consequat, sit amet luctus metus iaculis. Ut ut ex quis nulla pulvinar scelerisque. Nulla facilisis eros dui, id facilisis metus tempor rhoncus. Maecenas elementum tempor ante, fermentum aliquet quam lacinia sed. Praesent ligula ex, iaculis vestibulum massa eu, dapibus volutpat libero. Donec tempor odio imperdiet odio maximus, at pharetra nunc viverra. Vestibulum at condimentum sem, ac feugiat sapien. Nulla rutrum auctor mauris, nec placerat massa auctor quis. Praesent et magna pretium, interdum ante sit amet, molestie metus. Fusce feugiat justo nec libero volutpat varius. Aenean dictum, nisl a feugiat rutrum, mauris felis ultricies metus, ut lobortis felis lectus non dolor.

Mauris in posuere nisi, a vehicula sapien. Integer tristique convallis porttitor. Curabitur mauris mi, efficitur ut congue vitae, posuere non nulla. Nunc sed sem eu ligula maximus sodales nec in purus. Cras sodales augue quis scelerisque accumsan. Aenean dignissim diam vel ligula lobortis, nec convallis mi ornare. Fusce libero libero, faucibus ut enim sit amet, bibendum finibus erat. Sed ultrices rhoncus diam semper laoreet.

Quisque eu massa turpis. Aenean bibendum ex vitae dolor vehicula, vitae vulputate quam fringilla. Phasellus interdum sit amet quam ac placerat. Donec mollis aliquam velit. Nulla ultricies iaculis felis ut rutrum. Suspendisse commodo mi eu risus malesuada egestas. Praesent semper mi id eros pretium, nec sagittis odio semper. Fusce nec volutpat velit. Sed cursus maximus mi quis laoreet. Nam ac nisl id massa varius viverra. Aliquam molestie risus a quam maximus, non lobortis velit bibendum. Nullam sed magna nec neque porttitor ultricies.

Praesent venenatis eu dolor eget congue. Sed sed suscipit nulla. Nullam sit amet luctus nibh. Nam posuere ut tortor id ultricies. Sed ornare erat suscipit turpis venenatis, non aliquam massa convallis. Aliquam erat volutpat. Aenean eu turpis sit amet magna porta sodales. Nam scelerisque a lorem at venenatis. Integer at efficitur justo. Proin porttitor sagittis sodales. Proin auctor nulla neque, quis aliquet ipsum laoreet ac. Etiam non ultrices arcu, in lobortis augue. Fusce sed porta massa, quis semper sapien. Morbi rhoncus congue purus quis dapibus. Nulla ultricies dolor massa, sit amet auctor tellus ultrices sed.

Phasellus non metus tincidunt, faucibus enim elementum, semper nibh. Nunc eu velit vitae dui lobortis maximus. Vestibulum interdum, risus id efficitur pretium, purus magna facilisis mauris, at malesuada leo nisi nec sem. Maecenas scelerisque venenatis orci vitae gravida. Nullam pretium mattis sapien in imperdiet. Nullam congue, tellus ac tempus tincidunt, orci tellus bibendum felis, at accumsan felis nulla porttitor sapien. Fusce quis ex in mi dignissim lobortis. Aenean aliquet pretium tortor, sed finibus urna tempor ut. Aenean iaculis est sit amet malesuada porta. Praesent consequat, urna a aliquam placerat, nulla est elementum tellus, vitae feugiat velit velit eget sapien. Phasellus sagittis rhoncus dignissim.

Proin eget lacinia erat. Vivamus elementum porta molestie. Proin vestibulum, nunc id vulputate varius, arcu nisi imperdiet mi, vel facilisis velit lacus sit amet nisi. Aenean ut nunc ac mauris consectetur volutpat. Cras vel dui tincidunt, interdum tortor ac, euismod odio. Aliquam sit amet molestie ipsum. Integer orci augue, cursus at nibh eu, efficitur pulvinar ex. Aenean ac dui quis ipsum vestibulum dapibus in ac ante. Aenean facilisis turpis et nisl consequat malesuada. Ut quis volutpat est. Donec nec sollicitudin ipsum.

Proin mollis mollis diam, sit amet porta metus aliquet eu. Sed egestas nunc suscipit lacinia scelerisque. Vivamus porta euismod dignissim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce cursus, dolor id pulvinar porttitor, ex tortor rutrum dui, quis sagittis lacus nisl at diam. Vivamus eget elementum nisi, a consequat erat. Vivamus eu purus non massa pretium luctus in quis urna. Nullam consectetur id odio sit amet hendrerit.

Maecenas ornare diam neque, non pharetra ex imperdiet in. In accumsan nec nibh id imperdiet. Nam ante dui, egestas vitae interdum nec, venenatis a tellus. Sed sagittis dolor quam, at dictum turpis imperdiet id. Phasellus a enim odio. Cras finibus ante vitae consectetur commodo. Donec ut metus ut lacus viverra ornare at id nunc. Sed turpis tellus, consequat eu placerat sed, tincidunt sit amet augue. Vivamus sit amet eros vel dui sodales pulvinar. Nam auctor, ante aliquet sagittis dignissim, lectus nisl efficitur nunc, sed molestie eros orci vitae dui. Etiam semper elit quis orci iaculis fringilla. Donec ut varius dolor, eget eleifend nunc.

Cras a turpis fringilla, bibendum dui a, eleifend augue. Phasellus scelerisque sollicitudin ullamcorper. Aenean quis porta nunc. Nunc laoreet risus velit, eget accumsan erat iaculis finibus. Sed elementum a lectus vel scelerisque. Sed pharetra tellus mi, a porta orci porta sed. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla id felis imperdiet, consequat neque non, convallis sem. Donec consequat, magna sit amet pretium consectetur, nulla augue pretium est, quis dictum dui erat eu tortor. Cras quis eros blandit, rutrum lacus vitae, volutpat sem. Aenean at facilisis nibh. Fusce blandit nulla non ornare aliquam. Nullam semper dui id nibh iaculis, ut aliquet nunc venenatis. Sed hendrerit viverra ex feugiat vehicula. Ut et nisi id leo efficitur faucibus sodales ac nisi.

Vestibulum congue tellus tortor, vel mollis massa posuere sit amet. Nullam pellentesque mi in tincidunt iaculis. Vestibulum mollis tortor libero, eget volutpat urna faucibus et. Nullam imperdiet elementum tellus non facilisis. Pellentesque porta placerat erat, in varius diam sodales vitae. Aliquam imperdiet blandit auctor. Aenean congue nibh quis gravida finibus. Quisque tempus porta massa nec feugiat. Morbi auctor venenatis orci, at efficitur augue pellentesque at. In viverra maximus libero vitae volutpat. Ut viverra nec enim sit amet hendrerit. Proin in nisi sem. Nullam mattis ex dapibus sem sodales, sed semper risus tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In quis ipsum dolor. Proin blandit ac mauris a vestibulum.

Mauris a nisi turpis. Maecenas et elementum neque. Ut in vestibulum mauris, ut eleifend ante. Vestibulum luctus condimentum venenatis. Aenean eu consectetur justo. Nullam ante justo, scelerisque ut turpis eu, consequat molestie quam. Nulla erat turpis, tempor at nulla at, interdum fermentum ante. Morbi molestie aliquet nisl, at suscipit lacus tincidunt at. Duis eget facilisis felis. Phasellus id dolor sollicitudin, dapibus quam sit amet, egestas neque.
      <button onClick={()=>navigate(-1)}>go back</button>
    </div>
  );
}

export default About;
